# sample libonomy config file
# use the config flag to start a node with a config file.
# e.g $./go-libonomy --config ./config.toml
# cli flags will get a higher priority than configured in the file.

# Main Config
[main]
data-folder = "~/.libonomy-data"
test-mode = false

# Node Config
[p2p]
security-param = 20
fast-sync = true
tcp-port = 7513
node-id = ""
new-node= false
dial-timeout = "1m"
conn-keepalive = "48h"
network-id = 1 # 0 - MainNet, 1 - TestNet
response-timeout = "2s"
session-timeout = "2s"
max-pending-connections = 50
target-outbound = 10
max-inbound = 100
buffer-size = 100
peers-file = "peers.json" # located under data-dir/<publickey>/<peer-file> not loaded or save if empty string is given.

# Node Swarm Config
[p2p.swarm]
bootstrap = false
bucketsize = 20 # Routing table bucket size
alpha = 3 # Routing table alpha
randcon = 2 # Number of random connections
bootnodes = [] # example : libonomy://j7qWfWaJRVp25ZsnCu9rJ4PmhigZBtesB4YmQHqqPvt@0.0.0.0:7517?disc=7517

# Time sync NTP Config
[time]
max-allowed-time-drift = "10s"
ntp-queries = 5
default-timeout-latency = "10s"

[logging]
p2p = "info"
